# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.16.1 ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installation
        run: npm ci

      - name: Build NgxEasyTable
        run: npm run build:ngx-easy-table
        env:
          CI: true

      - name: Linter
        run: npm run lint

      - name: Send coverage to Coverall
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/ngx-easy-table/lcov.info

      - name: "Publish @paddls/ngx-easy-table"
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^release: v(\\S+)"
          workspace: "./dist/ngx-easy-table"
          publish_args: "--access public"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_PADDLS }}
